import * as assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";

const parserPath = "lib/ai/minimax-event-parser.ts";
const routePath = "app/api/record-event/route.ts";
const recordParserPath = "lib/ai/minimax-record-parser.ts";
const recordRoutePath = "app/api/record-input/route.ts";

assert.equal(existsSync(parserPath), true);
assert.equal(existsSync(routePath), true);
assert.equal(existsSync(recordParserPath), true);
assert.equal(existsSync(recordRoutePath), true);

const parser = readFileSync(parserPath, "utf8");
const route = readFileSync(routePath, "utf8");
const recordParser = readFileSync(recordParserPath, "utf8");
const recordRoute = readFileSync(recordRoutePath, "utf8");

assert.match(parser, /MINIMAX_API_KEY/);
assert.match(parser, /OPENAI_API_KEY/);
assert.match(parser, /OPENAI_BASE_URL/);
assert.match(parser, /MINIMAX_MODEL/);
assert.match(parser, /MiniMax-M3/);
assert.match(parser, /response_format/);
assert.match(parser, /json_object/);
assert.match(parser, /parseMiniMaxEventInput/);
assert.match(parser, /timeoutMs/);
assert.match(parser, /AbortSignal\.timeout/);
assert.match(parser, /extractMiniMaxJsonContent/);
assert.match(parser, /JSON\.parse\(extractMiniMaxJsonContent\(content\)\)/);
assert.match(parser, /```json/);
assert.match(parser, /endsAt 可以是 null/);
assert.match(parser, /create_event 必须有 title 和 startsAt/);
assert.match(parser, /delete_event/);
assert.match(parser, /targetDate/);
assert.match(parser, /title 必须是用户真正要记录或删除的事项名/);
assert.match(parser, /我要健身/);
assert.match(parser, /title=健身/);
assert.match(parser, /帮我把周六下午四点的会议删掉/);
assert.match(parser, /startsAt=2026-06-20T16:00:00\+08:00/);
assert.match(parser, /events/);
assert.match(parser, /event/);
assert.match(parser, /normalizeMiniMaxDateTime/);

assert.match(route, /export async function POST/);
assert.match(route, /parseMiniMaxEventInput/);
assert.match(route, /payload\.now/);
assert.match(route, /NextResponse\.json/);

assert.match(recordParser, /parseMiniMaxRecordInput/);
assert.match(recordParser, /create_ledger/);
assert.match(recordParser, /amountCents/);
assert.match(recordParser, /direction/);
assert.match(recordParser, /category/);
assert.match(recordParser, /occurredAt/);
assert.match(recordParser, /默认记为当前时间/);
assert.match(recordParser, /金额是多少？/);
assert.match(recordParser, /这是收入还是支出？/);
assert.match(recordParser, /语义审阅/);
assert.match(recordParser, /不要按关键词或正则猜测/);
assert.match(recordParser, /先理解用户真正想记录的对象、时间、金额和上下文/);
assert.match(recordParser, /只输出符合 schema 的 JSON/);
assert.match(recordParser, /缺失关键信息时使用 needs_clarification/);
assert.match(recordParser, /不要把自然语言原句直接塞进 title/);
assert.match(recordParser, /即使用户没有说明货币单位/);
assert.match(recordParser, /花了我600/);
assert.match(recordParser, /600 返回 60000/);
assert.match(recordParser, /出行表达也是事件/);
assert.match(recordParser, /下个月六号我要去广州，六点的飞机/);
assert.match(recordParser, /startsAt: "2026-07-06T06:00:00\+08:00"/);
assert.match(recordParser, /logMiniMaxRawContent\(content\)/);
assert.match(recordParser, /process\.env\.NODE_ENV !== "production"/);
assert.match(recordParser, /console\.log\("【MiniMax 原始返回】:", content\)/);
assert.match(recordParser, /Math\.round/);
assert.match(recordParser, /parseInt\(value, 10\)/);
assert.match(recordParser, /intent: "needs_clarification"/);

assert.match(recordRoute, /export async function POST/);
assert.match(recordRoute, /parseMiniMaxRecordInput/);
assert.match(recordRoute, /payload\.now/);
assert.match(recordRoute, /NextResponse\.json/);
